/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bitcoinj_jni_KeyCrypterJNI */

#ifndef _Included_org_bitcoinj_jni_KeyCrypterJNI
#define _Included_org_bitcoinj_jni_KeyCrypterJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bitcoinj_jni_KeyCrypterJNI
 * Method:    deriveKey_jni
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_bitcoinj_jni_KeyCrypterJNI_deriveKey_1jni
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_bitcoinj_jni_KeyCrypterJNI
 * Method:    decrypt_jni
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_bitcoinj_jni_KeyCrypterJNI_decrypt_1jni
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     org_bitcoinj_jni_KeyCrypterJNI
 * Method:    encrypt_jni
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_bitcoinj_jni_KeyCrypterJNI_encrypt_1jni
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
