/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bitcoinj_jni_KeyCrypterJNI_KeyParameter */

#ifndef _Included_org_bitcoinj_jni_KeyCrypterJNI_KeyParameter
#define _Included_org_bitcoinj_jni_KeyCrypterJNI_KeyParameter
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
